import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"
import typescript from "@rollup/plugin-typescript"

const path = require("path")

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react({
      jsxImportSource: "@emotion/react",
      jsxRuntime: "automatic",
      babel: {
        plugins: ["@emotion/babel-plugin"],
        compact: false,
      },
      // Exclude storybook stories
      exclude: [
        /\.stories\.([tj])sx?$/,
        /\.e2e\.([tj])sx?$/,
        /\.test\.([tj])sx?$/,
      ],
      // Only .tsx files
      include: ["**/*.tsx", "**/*.ts"],
    }),
  ],
  build: {
    sourcemap: true,
    minify: false,
    lib: {
      entry: path.resolve(__dirname, "src/index.ts"),
      name: "@illa-design/react",
      fileName: (format) => `${format}/index.js`,
    },
    rollupOptions: {
      plugins: [
        typescript({
          tsconfig: path.resolve(__dirname, "tsconfig.json"),
          rootDir: path.resolve(__dirname, "src"),
          declaration: true,
          declarationDir: path.resolve(__dirname, "dist/types"),
          exclude: path.resolve(__dirname, "node_modules/**"),
        }),
      ],
      external: [
        "react",
        "react-dom",
        "@illa-design/avatar",
        "@illa-design/icon",
        "@illa-design/image",
        "@illa-design/system",
        "@illa-design/tag",
        "@illa-design/theme",
        "@illa-design/divider",
        "@illa-design/space",
        "@illa-design/button",
        "@illa-design/radio",
        "@illa-design/typography",
        "@illa-design/trigger",
        "@illa-design/input",
        "@illa-design/input-number",
        "@illa-design/tooltip",
        "@illa-design/popover",
        "@illa-design/link",
        "@illa-design/config-provider",
        "@illa-design/progress",
        "@illa-design/empty",
        "@illa-design/badge",
        "@illa-design/statistic",
        "@illa-design/checkbox",
        "@illa-design/list",
        "@illa-design/switch",
        "@illa-design/alert",
        "@illa-design/input-tag",
        "@illa-design/select",
        "@illa-design/grid",
        "@illa-design/pagination",
        "@illa-design/upload",
        "@illa-design/spin",
        "@illa-design/notification",
        "@illa-design/popconfirm",
        "@illa-design/description",
        "@illa-design/timeline",
        "@illa-design/card",
        "@illa-design/message",
        "@illa-design/rate",
        "@illa-design/affix",
        "@illa-design/comment",
        "@illa-design/tabs",
        "@illa-design/time-picker",
        "@illa-design/calendar",
        "@illa-design/skeleton",
        "@illa-design/modal",
        "@illa-design/back-top",
        "@illa-design/drawer",
        "@illa-design/table",
        "@illa-design/anchor",
        "@illa-design/collapse",
        "@illa-design/date-picker",
        "@illa-design/result",
        "@illa-design/page-header",
        "@illa-design/slider",
        "@illa-design/menu",
        "@illa-design/tree-common",
        "@illa-design/tree-select",
      ],
      output: {
        globals: {
          react: "React",
          "react-dom": "ReactDom",
          "@illa-design/avatar": "@illa-design/avatar",
          "@illa-design/icon": "@illa-design/icon",
          "@illa-design/image": "@illa-design/image",
          "@illa-design/system": "@illa-design/system",
          "@illa-design/tag": "@illa-design/tag",
          "@illa-design/theme": "@illa-design/theme",
          "@illa-design/divider": "@illa-design/divider",
          "@illa-design/space": "@illa-design/space",
          "@illa-design/button": "@illa-design/button",
          "@illa-design/radio": "@illa-design/radio",
          "@illa-design/typography": "@illa-design/typography",
          "@illa-design/trigger": "@illa-design/trigger",
          "@illa-design/input": "@illa-design/input",
          "@illa-design/input-number": "@illa-design/input-number",
          "@illa-design/tooltip": "@illa-design/tooltip",
          "@illa-design/popover": "@illa-design/popover",
          "@illa-design/link": "@illa-design/link",
          "@illa-design/config-provider": "@illa-design/config-provider",
          "@illa-design/progress": "@illa-design/progress",
          "@illa-design/empty": "@illa-design/empty",
          "@illa-design/badge": "@illa-design/badge",
          "@illa-design/statistic": "@illa-design/statistic",
          "@illa-design/checkbox": "@illa-design/checkbox",
          "@illa-design/list": "@illa-design/list",
          "@illa-design/switch": "@illa-design/switch",
          "@illa-design/alert": "@illa-design/alert",
          "@illa-design/input-tag": "@illa-design/input-tag",
          "@illa-design/select": "@illa-design/select",
          "@illa-design/grid": "@illa-design/grid",
          "@illa-design/pagination": "@illa-design/pagination",
          "@illa-design/upload": "@illa-design/upload",
          "@illa-design/spin": "@illa-design/spin",
          "@illa-design/notification": "@illa-design/notification",
          "@illa-design/popconfirm": "@illa-design/popconfirm",
          "@illa-design/description": "@illa-design/description",
          "@illa-design/timeline": "@illa-design/timeline",
          "@illa-design/card": "@illa-design/card",
          "@illa-design/message": "@illa-design/message",
          "@illa-design/rate": "@illa-design/rate",
          "@illa-design/affix": "@illa-design/affix",
          "@illa-design/comment": "@illa-design/comment",
          "@illa-design/tabs": "@illa-design/tabs",
          "@illa-design/time-picker": "@illa-design/time-picker",
          "@illa-design/calendar": "@illa-design/calendar",
          "@illa-design/skeleton": "@illa-design/skeleton",
          "@illa-design/modal": "@illa-design/modal",
          "@illa-design/steps": "@illa-design/steps",
          "@illa-design/back-top": "@illa-design/back-top",
          "@illa-design/drawer": "@illa-design/drawer",
          "@illa-design/table": "@illa-design/table",
          "@illa-design/anchor": "@illa-design/anchor",
          "@illa-design/collapse": "@illa-design/collapse",
          "@illa-design/date-picker": "@illa-design/date-picker",
          "@illa-design/result": "@illa-design/result",
          "@illa-design/page-header": "@illa-design/page-header",
          "@illa-design/slider": "@illa-design/slider",
          "@illa-design/menu": "@illa-design/menu",
          "@illa-design/tree": "@illa-design/tree",
          "@illa-design/tree-select": "@illa-design/tree-select",
          "@illa-design/tree-common": "@illa-design/tree-common",
        },
      },
    },
  },
})
