export * from "./text"
export * from "./ellipsis-config"
export * from "./copyable-config"
export * from "./heading"
export * from "./paragraph"
export * from "./typography"
export * from "./interface"
